workflows:
  ios-unsigned-build:
    name: Build Unsigned iOS IPA
    environment:
      node: 20  # Yahan 18.x ki jagah 20 kar diya hai
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Generate Native iOS Code
        script: npx expo prebuild --platform ios --clean
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build Unsigned App
        script: |
          cd ios
          xcodebuild build -workspace Bookloop.xcworkspace -scheme Bookloop -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath build
          
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/Bookloop.app Payload/
          zip -r Bookloop.ipa Payload
    artifacts:
      - ios/Bookloop.ipa